#ifndef JBUTTONSTATE_H_INCLUDED
#define JBUTTONSTATE_H_INCLUDED

enum JButtonState
{
    MOUSE_OUT = 0,
    MOUSE_OVER = 1,
    MOUSE_DOWN = 2,
    MOUSE_UP = 3,
    MOUSE_TOTAL_STATE = 4
};

#endif // JBUTTONSTATE_H_INCLUDED
